#!/bin/bash
#SBATCH --job-name=sweep_bin16um_logmu
#SBATCH --output=/dcs04/hicks/data/Jan/sim_project/sim_paper/code/data/logs/sweep_bin16um_logmu_%A_%a.out
#SBATCH --array=0-2
#SBATCH --time=08:00:00
#SBATCH --mem=320G
#SBATCH --cpus-per-task=4
#SBATCH --partition=shared
#
# First pass at a bin_size_um=16 count-distribution calibration sweep, testing
# whether a coarser real-Visium-HD-standard bin (vs. the manuscript-baseline
# 8um) gets bin's count distributions closer to real without further tuning
# tricks -- motivated by two 8um findings in figure.md (2026-08-25): (1) bin's
# near-binary empty/non-empty sampling comes from the 8um bin being comparable
# in scale to --cell-r-mean=7.5um (the radius smoke test showed larger
# molecule-spillover radius alone reduces empty bins but plateaus without
# reaching a real unimodal genes-per-bin shape); (2) bin's weak domain
# compositional signal for BANKSY domain recovery is the same
# aggregation-reveals-composition mechanism that made spot's domain ARI jump
# 5x under the strong domain mix -- a bigger bin footprint pools more cells.
#
# Anchored on the already-validated 8um packing fraction (packing_pf0p04,
# sphere_r_um=2050 -- this is a 3D packing property, independent of bin size,
# so it carries over) and the same theta/theta_jitter/noise_scale/
# marker_foldchange defaults bin_vs_breast_cancer_visium_hd.sh uses (untouched
# at 8um: theta=2.0, theta_jitter=1.0, noise_scale=1.3, marker_foldchange=3.5
# -- the marker-branch/theta_jitter issues were Panel A-cell-specific fixes,
# explicitly left alone for bin, see figure.md 2026-08-24). Only base_gene_lognormal's
# log_mu is swept here, shifted down from 8um's winning log_mu=0.0 to account for
# a 16um bin covering ~4x the area (so ~4x more expected counts/bin at the same
# log_mu) -- this is a first, coarse pass (3 points) to bracket the right range;
# narrow further once these land.
#
# Real comparison target: 16um SpotSweeper-QC'd references generated by
# code/real_data_qc/misc/run_visium_hd_qc_16um.sh (job 35194892), same pipeline
# as the existing 8um real_data_qc/*_visium_hd references, just
# --bin-size-um 16 against the square_016um binned_outputs already on disk (no
# new download -- 10x ships 2um/8um/16um together).
#
# Uses qc_filtered mode only (not the full 4-mode figure_2 sweep) since this is
# an exploratory bracketing pass, not a finalized Figure 2 panel -- qc_filtered
# is the mode historically cited for theta_hat/mean-variance judgments (HVG modes
# are panel-matching diagnostics, see figure.md "figure_2/ regeneration" notes).

set -euo pipefail

mkdir -p /dcs04/hicks/data/Jan/sim_project/sim_paper/code/data/logs
source /dcs04/hicks/data/Jan/sim_project/sim_paper/code/count_distribution/_env.sh
cd /dcs04/hicks/data/Jan/sim_project

LOG_MUS=(-2.5 -1.5 -0.5)
LOG_MU="${LOG_MUS[${SLURM_ARRAY_TASK_ID:-0}]}"
TAG="packing_pf0p04_bin16um_log_mu_${LOG_MU}"
MODALITY="bin"

SIM_RAW="sim_paper/data/noisy/${TAG}/simulation_${MODALITY}_z.h5ad"
SIM_QC="sim_paper/data/noisy/${TAG}/simulation_${MODALITY}_z_qc.h5ad"
OUT_ROOT="sim_paper/data/count_distribution/sweeps/bin16um_logmu_sweep"

echo "[config] log_mu=${LOG_MU} tag=${TAG}"

if [[ ! -f "${SIM_RAW}" ]]; then
    echo "[generate] ${TAG} not found, generating"
    "${PYTHON_BIN}" sim_paper/code/data/generate_simulation_noisy.py \
        --modality "${MODALITY}" \
        --sphere-r-um 2050 \
        --bin-size-um 16 \
        --base-gene-lognormal "${LOG_MU}" 0.7 \
        --out-tag "${TAG}"
fi

if [[ ! -f "${SIM_QC}" ]]; then
    echo "[qc] ${SIM_QC} not found, running 00_qc_filter.py"
    "${PYTHON_BIN}" sim_paper/code/clustering/00_qc_filter.py --modality "${MODALITY}" --packing-tag "${TAG}"
fi

for real in breast_cancer_visium_hd human_pancreas_visium_hd; do
    echo "[compare] ${TAG} vs ${real}_16um (qc_filtered)"
    "${PYTHON_BIN}" sim_paper/code/count_distribution/count_distribution.py \
        --modality "${MODALITY}" --input "${SIM_QC}" \
        --compare-input "sim_paper/data/real_data_qc/${real}_16um/${real}_qc.h5ad" \
        --compare-label "${real}_16um" \
        --output-dir "${OUT_ROOT}/${TAG}_qc_filtered_vs_${real}_16um"
done

echo "[done] ${TAG}"
